[profile.default]
src = 'contracts'
test = 'test'
out = 'out'
libs = ['lib']
solc = '0.8.20'
evm_version = 'shanghai'

remappings = [
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'forge-std/=lib/forge-std/src/',
    'ds-test/=lib/forge-std/lib/ds-test/src/'
]
